spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://172.30.1.2:3306/local?serverTimezone=Asia/Seoul'
    username: 'root'
    password: '1q2w3e4r1!'
  jpa:
    hibernate:
      ddl-auto: validate
      properties: # property 사용 설정
        hibernate: # hibernate property 설정
          format_sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:data.sql
      mode: never

jwt:
  secret-key: 46JbihOdxPozmM17F0NoY174+=s4Sp90NtaUhbFzHe1t+LDwZ95jQ=


server:
  address: 0.0.0.0
  servlet:
    encoding:
      charset: UTF-8


file:
  localPath: static/files
  minIO:
    endpoint: http://172.30.1.12
    port: 9000
    accessKey: admin
    secretAccessKey: password
    defaultBucketName: blog


logging:
  level:
    org:
      springframework: info